name: development
on: 
  push:
    branches:
      - master
  workflow_dispatch:   
env:
  DATABASE_USERNAME: ${{ secrets.USERNAME }}
  global-level: ${{ vars.global_level }} 
jobs:
  checkout-job:
     runs-on: self-hosted
     steps:
       - name: checking out code
         uses: actions/checkout@v4      
  infra-build:
     runs-on: self-hosted
     needs: checkout-job     
     steps:
       - name: list the directory in target folder
         run: ls -lrt      
       - name: Navigate to the Terraform code Directory
         run: |
              cd terrform-code      
              terraform init 
              terraform apply -auto-approve
              terraform output -json > terraform-output.json
       - name: ssh-ip
         run: |
           chmod 775 ssh-ip.sh
           ./ssh-ip.sh
       - name: docker container execute
         run: |
           chmod 775 docker-run.sh
           ./docker-run.sh	              
  app-build:
     env:
        job-level: ${{ vars.job_level }}
     needs: infra-build
     runs-on: self-hosted
     steps: 
       - name: Read Terraform Output
         run: |
             INSTANCE_NAMES=$(jq -r '.instance_names.value' terrform-code/terraform-output.json)
             echo "Instance Names: $INSTANCE_NAMES"
       - name: list the content of the directory
         run: echo "This is ${{ env.global-level }} , ${{ env.job-level }} and ${{ env.step-level }} variables in a single shell command" 
       - name: build of the application
         run: mvn clean install
         env:
             step-level: ${{ vars.step_level }}                
  package-upload:
     needs: app-build
     runs-on: self-hosted
     steps: 
       - name: list the directory in target folder
         run: ls -lrt target
       - name: upload war file package
         uses: actions/upload-artifact@v4
         with:
           name: war-file
           path: target/spring-boot-app-1.4.0.RELEASE.jar
  docker-image-build:
    needs: package-upload
    runs-on: self-hosted
    steps: 
       - name: download war file package
         uses: actions/download-artifact@v4  
         with:
           name: war-file         
       - name: echo the database username
         run: echo "$DATABASE_USERNAME"
       - name: Set up Docker Buildx
         run: docker build -t haciac.azurecr.io/hce:${{ github.run_number }}-DEV .
       - name: Docker Push Image to registry 
         run:  docker push haciac.azurecr.io/hce:${{ github.run_number }}-DEV
  docker-image-deployment:
    needs: docker-image-build
    runs-on: self-hosted
    steps: 			  
       - name: application deployment 
         run: |
           chmod 775 application-run.sh
           ./application-run.sh	
