name: development
on: 
  push:
    branches:
      - master
  workflow_dispatch:  
env:
  DATABASE_USERNAME: ${{ secrets.USERNAME }}
  global-level: ${{ vars.global_level }} 
jobs:
  checkout-job:
     runs-on: self-hosted
     steps:
       - name: checking out code
         uses: actions/checkout@v4      
  infra-build:
     runs-on: self-hosted
     steps:
       - name: list the directory in target folder
         run: ls -lrt      
       - name: Navigate to the Terraform code Directory
         run: cd terrform-code
       - name: Initialize Terraform
         run:  terraform init		 
       - name: Apply Terraform changes
         run: terraform apply -auto-approve	 
